In [43]:
import torch
import numpy as np

### Tensor

**x.add(y)与x.add_(y)**             加法

In [8]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
z = x.add(y) ## 不改变x
print(x)
print(y)
print(z)
x.add_(y) ## 改变x
print(x)

tensor([1, 2])
tensor([3, 4])
tensor([4, 6])
tensor([4, 6])


In [11]:
torch.Tensor([1,2,3,4,5,6])
torch.Tensor(3,5)
t = torch.Tensor([[1,2,3],[4,5,6]])
t.size()  #查看形状
t.shape #等价
torch.Tensor(t.size())

tensor([[-3.0329e-36,  1.3466e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

**torch.Tensor v.s. torch.tensor**

**修改形状**

In [32]:
x = torch.randn(2,3)
x.size()

torch.Size([2, 3])

In [17]:
x

tensor([[ 1.0018,  1.4806, -0.3129],
        [ 0.5637,  0.0371, -1.0389]])

In [15]:
x.dim()

2

In [30]:
x.view(3,2) #不改变x

tensor([[ 1.0018,  1.4806],
        [-0.3129,  0.5637],
        [ 0.0371, -1.0389]])

In [18]:
x

tensor([[ 1.0018,  1.4806, -0.3129],
        [ 0.5637,  0.0371, -1.0389]])

In [22]:
y = x.view(-1)
y.shape

torch.Size([6])

In [28]:
z = torch.unsqueeze(y,0)
print(z)
z.size()

tensor([[ 1.0018,  1.4806, -0.3129,  0.5637,  0.0371, -1.0389]])


torch.Size([1, 6])

In [34]:
z.numel()  #number of elements

6

**torch.view v.s. torch.reshape**

**索引**

In [38]:
torch.manual_seed(100) #随机数种子
x = torch.randn(2,3)
print(x[0,:])
print(x[:,-1])

tensor([ 0.3607, -0.2859, -0.3938])
tensor([-0.3938, -2.3134])


In [40]:
mask=x>0
torch.masked_select(x,mask)  # (input,mask)
torch.nonzero(mask)
index = torch.LongTensor([[0,1,1],[1,1,1]])
a = torch.gather(x,1,index)
z = torch.zeros(2,3)

In [41]:
z.scatter_(1,index,a)

tensor([[ 0.3607, -0.2859,  0.0000],
        [ 0.0000, -1.3833,  0.0000]])

**广播机制**：允许不同形状或大小的数组进行数学运算

In [58]:
A = np.arange(0,40,10).reshape(4,1)
B = np.arange(0,3)
print("A:",A)
print("B:",B)
# 转换为Tensor
A1 = torch.from_numpy(A)  
B1 = torch.from_numpy(B)  #形状为3
print("A1:",A1)
print("B1:",B1)
C = A1+B1  #Tensor自动实现广播
B2 = B1.unsqueeze(0) #变成一行
print("B2:",B2)
A2 = A1.expand(4,3) #重复数组
B3 = B2.expand(4,3)
print("A2:",A2)
print("B3:",B3)
C = A2+B3
print(C)

A: [[ 0]
 [10]
 [20]
 [30]]
B: [0 1 2]
A1: tensor([[ 0],
        [10],
        [20],
        [30]], dtype=torch.int32)
B1: tensor([0, 1, 2], dtype=torch.int32)
B2: tensor([[0, 1, 2]], dtype=torch.int32)
A2: tensor([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30]], dtype=torch.int32)
B3: tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]], dtype=torch.int32)
tensor([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]], dtype=torch.int32)


**逐元素操作**

In [65]:
t = torch.randn(1,3)
t1 = torch.randn(3,1)
t2 = torch.randn(1,3)
print(t)
print(t1)
print(t2)
torch.addcdiv(t,0.1,t1,t2)  #这里t1和t2做的是矩阵乘法

tensor([[ 0.5895, -0.3747, -1.2307]])
tensor([[ 1.5123],
        [-0.7597],
        [ 0.6139]])
tensor([[-0.9933, -1.1286, -0.8027]])


tensor([[ 0.4373, -0.5087, -1.4191],
        [ 0.6660, -0.3074, -1.1361],
        [ 0.5277, -0.4291, -1.3072]])

In [61]:
torch.sigmoid(t)

tensor([[0.4357, 0.4376, 0.6170]])

In [62]:
torch.clamp(t,0,1)

tensor([[0.0000, 0.0000, 0.4770]])

In [63]:
t.add_(2)

tensor([[1.7414, 1.7490, 2.4770]])

**clamp**

In [67]:
import torch
 
a = torch.arange(9).reshape(3, 3)   # 创建3*3的tensor
b = torch.clamp(a, 3, 6)     # 对a的值进行限幅，限制在[3, 6]
print('a:', a)
print('shape of a:', a.shape)
print('b:', b)
print('shape of b:', b.shape)

a: tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
shape of a: torch.Size([3, 3])
b: tensor([[3, 3, 3],
        [3, 4, 5],
        [6, 6, 6]])
shape of b: torch.Size([3, 3])
